platform :ios, '14.0'
use_frameworks!

project 'CocoapodsDemo.xcodeproj'

def player_sdk_pods
  pod 'BambuserPlayerSDK', '1.2.1'
end

target 'Demo-SwiftUI' do
  player_sdk_pods
end

target 'Demo-UIKit' do
  player_sdk_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|

      if target.product_name == "gRPCCertificates-Cpp" or target.product_name == "BambuserPlayerSDK_BambuserPlayerBundle"
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
      
    end
  end
end
